name: Quality Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check HTML validity
        uses: Cyb3r-Jak/html-validate-action@v2
        with:
          path: .
